name: Update DB (schedule)
on:
  schedule:
    - cron: "0 21 * * *"
    
  workflow_dispatch:
jobs:
  update-db:
    runs-on: ubuntu-latest
    environment: update_crieur
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
        
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script
        env:
            DB_USER: ${{  secrets.DB_USER }}
            DB_PASSWORD: ${{  secrets.DB_PASSWORD }}
            DB_URL: ${{  secrets.DB_URL }}
            DB_NAME: ${{  secrets.DB_NAME }}
        run: python update_crieur.py
