name: Update Crieur
on:
  workflow_dispatch:
  push:
    branches:
    - main

jobs:
  update-db:
    runs-on: ubuntu-latest
    environment: update_crieur
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
        
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script
        env:
            DB_USER: ${{  secrets.DB_USER }}
            DB_PASSWORD: ${{  secrets.DB_PASSWORD }}
            DB_URL: ${{  secrets.DB_URL }}
            DB_NAME: ${{  secrets.DB_NAME }}
        run: python update_crieur.py
  
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
        
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: execute py script # run main.py
        run: python move_imgs.py
          
      - name: 'cloning node repo'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          repository: antoninfaure/node-180
          path: node-repo
          
      - name: 'move imgs'
        run: |
          cp -fr static node-repo
          
      - name: 'commit and push'
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.API_TOKEN_GITHUB }}@github.com/antoninfaure/node-180
          git config --unset-all http.https://github.com/.extraheader
          git add .
          git diff-index --quiet HEAD || git commit -m 'Update content' | git push origin main
        working-directory: 'node-repo'

