# This is a basic workflow that is manually triggered

name: Test
on:
  workflow_dispatch:

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
        
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: execute py script # run main.py
        run: python move_imgs.py
        
      - name: 'cloning node repo'
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          repository: antoninfaure/node-180
          path: node-repo

      - name: Create release branch
        run: git checkout -b release
        working-directory: 'node-repo'

      - name: 'move imgs'
        run: |
          cp -fr static/ node-repo

      - name: 'commit and push'
        env:
          GITHUB_TOKEN: ${{ secrets.API_TOKEN_GITHUB }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git remote set-url origin https://x-access-token:${{ secrets.API_TOKEN_GITHUB }}@github.com/antoninfaure/node-180
          git config --unset-all http.https://github.com/.extraheader
          git add .
          git commit -m "release"
          git push origin release
        working-directory: 'node-repo'
        
  pull-request:
    needs: copy-files
    runs-on: ubuntu-latest
    steps:
    - name: 'cloning node repo'
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.API_TOKEN_GITHUB }}
        repository: antoninfaure/node-180
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.API_TOKEN_GITHUB }}
        commit-message: Update content
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        branch: release
        delete-branch: true
