# This is a basic workflow that is manually triggered

name: Test
on:
  workflow_dispatch:

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
        
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: execute py script # run main.py
        run: python move_imgs.py
        
      - uses: actions/checkout@v2
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'temp'
          destination-github-username: 'antoninfaure'
          destination-repository-name: 'node-180'
          user-email: action@github.com
          target-branch: new_content
          target-directory: 'static/crieur'
