# This is a basic workflow that is manually triggered

name: Test
on:
  workflow_dispatch:

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
        
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: execute py script # run main.py
        run: python move_imgs.py
        
      - name: 'cloning node repo'
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          repository: antoninfaure/node-180
          path: node-repo

      - name: Create release branch
        run: git checkout -b release
        with:
          working-directory: './node-repo'
          token: ${{ secrets.API_TOKEN_GITHUB }}

      - name: 'move imgs'
        run: mv static/ -f node-repo/

      - name: 'commit'
        run: git commit -m "release"
        with:
          working-directory: './node-repo'
          token: ${{ secrets.API_TOKEN_GITHUB }}

      - name: Push new branch
        run: git push origin release
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
