# This is a basic workflow that is manually triggered

name: Test
on:
  workflow_dispatch:

jobs:
  copy-files:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner.
        
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: execute py script # run main.py
        run: python move_imgs.py
        
      - name: go to node-repo
        run: |
          mkdir node-repo
          cd node-repo
          ls 
          
      - name: 'cloning node repo'
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          repository: antoninfaure/node-180
          
      - name: 'move imgs'
        run: |
          cp -fr ../static/ .
          
      - name: 'commit'
        run: |
          
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "release"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.API_TOKEN_GITHUB }}
          commit-message: Update report
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          base: main
          branch: release
          branch-suffix: random
          delete-branch: true
          title: '[Example] Update report'
          body: |
            Update report
            - Updated with *today's* date
            - Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            report
            automated pr
          assignees: peter-evans
          reviewers: peter-evans
          team-reviewers: |
            owners
            maintainers
          milestone: 1
          draft: false
